# Generated by Django 4.2 on 2023-04-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=99)),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('option', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('path', models.CharField(max_length=60)),
                ('groups', models.CharField(max_length=2048)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
    ]
