# Generated by Django 4.2 on 2023-05-02 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=99)),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('option', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('path', models.CharField(max_length=60)),
                ('groups', models.CharField(max_length=2048)),
                ('label', models.CharField(max_length=100)),
                ('post_groups', models.ManyToManyField(to='marketplace.groups')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
        migrations.AddField(
            model_name='post',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='marketplace.state'),
        ),
    ]
