# Generated by Django 4.2 on 2023-05-02 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_groups_post_state_delete_posts_post_state_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Groups',
            new_name='Group',
        ),
    ]
