# Generated by Django 4.2 on 2023-05-03 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_post_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='label',
        ),
        migrations.RemoveField(
            model_name='post',
            name='option',
        ),
        migrations.RemoveField(
            model_name='post',
            name='type',
        ),
    ]
