# Generated by Django 4.2 on 2023-05-03 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_remove_post_description_remove_post_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='../img/')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='photos', to='marketplace.post')),
            ],
        ),
    ]
