# Generated by Django 4.2 on 2023-05-03 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_post_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='post',
            name='state',
        ),
    ]
